name: Use Multiple Secrets in Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Use secrets
      run: |
        echo "The first secret is $FIRST_SECRET"
        echo "The second secret is $SECOND_SECRET"
      env:
        FIRST_SECRET: ${{ secrets.MY_SECRET }}
        SECOND_SECRET: ${{ secrets.ANOTHER_SECRET }}
